Jenkinsfile

- Add steps only to build images (no running end to end tests at the moment) so we are able to deploy the application in TEST environment.

PP-2809  Add Jenkinsfile

---

Jenkinsfile

- Change deploy to do in ECS cluster.

PP-2809 Jenkins deploy to ECS

---

Dockerfile
build-local.sh

- Following same pattern as https://github.com/alphagov/pay-selfservice

PP-2809 Fix npm start failing not finding node_modules

---

Dockerfile
chamber.sha256sum
docker-startup.sh
update-chamber.sh

This PR adds [Chamber](https://github.com/segmentio/chamber) integration as part of Docker image.
Based on following PR: https://github.com/alphagov/pay-selfservice/pull/551
Related PR: https://github.com/alphagov/pay-direct-debit-connector/pull/12
Please see commits for more information.

PP-2905 Added Chamber to support AWS EC2 parameter store

---

Dockerfile
docker/build_and_test.Dockerfile

some minor security fixes, should also upgrade alpine base layer

PP-2851 Update Node to 6.12.0

---

README.md

- Add env variables to README.md (**PORT** and **NODE_WORKER_COUNT**)

PP-2809 Add env variables to README.md

---

Dockerfile

- Removed uneccessary python make g++ deps in docker file

PP-3004 Remove undeeded docker deps

---

app/secure/post.controller.tests.js
common/classes/PaymentRequest.class.js
test/fixtures/payments-fixtures.js

See commit message. Also thanks @maxcbc for being a human linter.

PP-3106 Appease linter by removing unused dependency

---

.nycrc
package.json

Removed nyc from test config as we don't use it

Removed NYC from local config

---

common/utils/metrics.js
package-lock.json
package.json
server.js
test/test.env

Collecting and sending out node metrics via the `appmetrics` package and statsd, similarly to how it is already done in the other node apps.

PP-3117 Add node metrics

---

Jenkinsfile

E2e will be re-enabled after naxsi changes and chamber changes are in

PP-2939 Temporarily disable e2e on merge

---

Dockerfile
docker-startup.sh
run-with-chamber.sh

Convert direct debit frontend to use run-with-chamber
calling docker-startup script

PP-3174 Implement database migrations for ECS

---

app/confirmation/get.controller.tests.js
app/confirmation/get.njk
app/confirmation/index.js
app/confirmation/post.controller.tests.js
app/secure/get.post.controller.tests.js
app/setup/get.controller.tests.js
app/setup/get.njk
app/setup/index.js
app/setup/post.controller.tests.js
common/middleware/csrf.js
common/middleware/csrf.tests.js
package.json
test/test_helpers/cookie-helper.js

- Add CSRF middleware
- Add CSRF token value in forms for set up and confirmation routes

Pp 3257 CSRF tokens

---

Jenkinsfile

Split out the deployment of the microservice, smoke tests and tagging of
build into separate jobs
solo @belindac

PP-3527 Separate deployment, smoke test and tagging jobs [wip, no merge]

---

Jenkinsfile

Need to pass through repository name to tagDeployment
job

PP-3527 Fix repo name in Jenkinsfile

---

app/confirmation/get.njk
common/assets/sass/modules/_confirmation.scss
common/browsered/index.js
common/templates/includes/analytics.njk
common/templates/layout.njk
package.json
server.js

- adding basic google analtyics tracking (won't do anythin until we add
a tracking ID to the env)
- Added gaap-analytics so we can track virtual pageview of journey
completion (success)
- Setup virtual pageview when user submits confirmation of DD

PP-2949 - Setup google analytics for DD user flow

---

app/change-payment-method/get.controller.js
app/change-payment-method/get.controller.tests.js
app/change-payment-method/index.js
app/confirmation/get.controller.tests.js
app/confirmation/get.njk
app/direct-debit-guarantee/anchor.njk
app/router.js
app/setup/get.controller.js
app/setup/get.controller.tests.js
app/setup/get.njk
common/clients/connector-client.js

- Added parameter to the dd guarantee link to enable back button on
dd guarantee page
- Extracted the dd guarantee anchor into a template file

PP-3258 Fix dead links

---

app/confirmation/get.njk

PP-3553 - Pass test/live to analytics

---

app/request-denied/index.js
app/request-denied/post.controller.js
app/request-denied/post.controller.tests.js
app/router.js

Naxsi intercepts a request and tries to POST to `/request-denied` when triggered. This PR shows the standard error page (similarly to card frontend).

PP-3815 Show error page when naxsi says no

---

app/setup/get.njk

- Move text inside the No selection

PP-3745 Update frontend to match the design

---

Jenkinsfile

PP-3676 Add option for not running e2e on PR build

---

Dockerfile
docker/build_and_test.Dockerfile

Use nodejs from alpine 3.8
solo @belindac

PP-4035 Upgrade to alpine linux 3.8

---

Dockerfile

Upgrade to our latest Alpine Linux container, which includes nodejs 8.11.4
CI will save us

PP-4344: Update to Alpine Linux 3.8.1

---

common/utils/metrics.js
package-lock.json
package.json

Upgrade appmetrics
The `null` we were passing as the first argument was due to a bug in appmetrics-statsd by the looks of things. See https://github.com/RuntimeTools/appmetrics-statsd/commit/c7675db8bd6a8a9e3c6c287b242e2330f5620e75
I have no idea how to test this

Bau upgrade appmetrics

---

package-lock.json
package.json

PP-4904 - lint on pre commit hook

---

app/cancel/get.controller.tests.js
common/classes/Service.class.js
test/fixtures/payments-fixtures.js

_A brief description of the pull request:_
_Steps to test or reproduce:_

PP-5234: Get service name from service_name.en

---

common/classes/GatewayAccount.class.js
common/templates/layout.njk
test/fixtures/payments-fixtures.js

Nothing gets the service name from dd-connector now.

PP-5234: Get service name from adminusers

---

app/confirmation/get.njk
app/direct-debit-guarantee/get.njk
app/setup/get.njk
common/assets/sass/application.scss
common/templates/layout.njk
package-lock.json
package.json
server.js

Update templates to govuk-frontend 3.0
Basically just had to fix a few paths

govuk-frontend 3.0 upgrade

---

Gruntfile.js
app/cancel/get.controller.tests.js
app/confirmation/get.controller.tests.js
app/confirmation/post.controller.tests.js
app/setup/get.controller.tests.js
app/setup/post.controller.js
app/setup/post.controller.tests.js
common/browsered/field-validation.js
common/templates/layout.njk

3841f3d  - livereload on template changes makes developing easier
6aa2773 - org details didnt look right
48887c9 - lint fixes
1930d82 - fix issue that caused labels to multiply on multiple clicks
b7f0e0f - Add `blur` eventListener so that we can alert users earlier

PP-5265 - improve inline validation

---

package-lock.json
package.json

This 3.0 release includes numerous accessibility updates but most visually prominent is the all new colour scheme - https://designnotes.blog.gov.uk/2019/07/29/weve-made-the-gov-uk-design-system-more-accessible/

BAU - 3.0 is officially released now so can use proper npm version

---

app/confirmation/get.controller.js
app/confirmation/get.controller.tests.js
app/confirmation/get.njk

- Add email address to template
- Pass email to the template from get controller
- Add test to ensure email address is shown

PP-5532 Add email address to confirm mandate page

---

common/templates/layout.njk

Must be deployed after alphagov/pay-product-page#162

PP-5653 - add a link to statement in the footer

---

app/utils/logger-format.js
app/utils/logger.js

- include an `@version` property with a value of 1
- change the "logger" key to "logger_name"
- change "label" value to "directdebit-frontend"

PP-5735 Fix JSON logging style

---

.travis.yml

Adds a simple .travis.yml build configuration for running CI node build tasks.

Add .travis.yml CI build config
