alphagov/pay-direct-debit-frontend

- Dockerfile
- update-chamber.sh
- Added CHAMBER_URL build-time argument to the Dockerfile
- Modified update-chamber.sh to reflect the changes
Based on https://github.com/alphagov/pay-selfservice/pull/551
> PP-2905 Update Chamber improvements

- package.json
- server.js
- start.js
1. Remove `forever`
We don't need `forever` when running in Amazon EC2 Container Service.
Also, `forever@0.15.3` depends on `timespan` which has "Regular Expression Denial of Service (ReDoS)" vulnerability: https://snyk.io/vuln/npm:timespan:20170907
There is an issue open for `timespan` here: indexzero/TimeSpan.js#10 (not fixed).
2. Fix dependency problem
We were referencing non-existing "winston" dependency.
Added "pino" as a new logger.
> Remove forever and fix dependency problem

- app/confirmation/get.controller.js
- app/confirmation/get.controller.tests.js
- app/confirmation/get.njk
- app/confirmation/index.js
- app/confirmation/post.controller.js
- app/confirmation/post.controller.tests.js
- app/secure/post.controller.js
- app/setup/get.controller.js
- app/setup/get.controller.tests.js
- app/setup/get.njk
- app/setup/post.controller.js
- app/setup/post.controller.tests.js
- common/classes/Payer.class.js
- common/classes/PaymentRequest.class.js
- common/clients/connector-client.js
- common/config/cookies.js
- common/utils/middleware.js
- package.json
- server.js
- test/fixtures/payments-fixtures.js
- test/test.env
- test/test_helpers/cookie-helper.js
- Adding a few calls to the dd connector client, this should be merged after alphagov/pay-direct-debit-connector#39  because it builds on the changes in the token response made in that PR
- Adding support of cheerio in tests and restructuring them to use the awesome patterns by @maxcbc
- Adding fixtures for generating test data
- Sticking `ALL THE THINGS` in the cookie session right now - this is probably not what we want in the future but it's ok to get our e2e flow and unblocking lots of things in our pipeline
- Tests are by no mean exhaustive, they are covering the very basics and are more like a foundation on which we should keep building after we have a more defined structure
- Until connector is merged, test locally by checking out …
> PP-3106 Scaffolding for minimum viable payment journey

- docker/build_and_test.Dockerfile
Rollback of `build_and_test.Dockerfile` installed libraries.
Should fix:
```
Can't find Python executable "python"
```
also rolled back other libraries (originally presented)
Related PR: https://github.com/alphagov/pay-direct-debit-frontend/pull/26
> PP-2967 Rollback of "build and test" libraries

- server.js
- This seems to fix the ENOSPC error and hopefully will let us deploy frontend where the NODE_ENV variable will be production
_Steps to test or reproduce:_
> PP-2939 Temporarily disabling the nunjucks watcher

- Jenkinsfile
- server.js
- Adding a step in the jenkins pipeline to direct debit run end to end tests
- Re-enabling the nunjucks watcher, knowing that it will be disabled in jenkins (because `NODE_ENV` is set to production)
> PP-2939 Run e2e when merging to master

- server.js
The frontend containers on ECS have correctly NODE_ENV set to production - jenkins builds it with NODE_ENV=test, so disabling the watcher will fix the ENOSPC issue.
@jonheslop would be good to understand why enabling the watcher makes the docker container watch too many files :(
> PP-2939 Disable nunjucks' watcher again

- Jenkinsfile
Reverts alphagov/pay-direct-debit-frontend#33
We can re-enable end to end on merges as now it actually runs 🚀
> Revert "PP-2939 Temporarily disable e2e on merge"

- Jenkinsfile
The standard run-end-to-end-tests job is throttled to 2 concurrent builds max. This is slowing down a lot direct debit, as we often have to wait for 40+ min for other builds to finish, when we don't need to.
There is a new job in Jenkins which just runs dd tests, and it is not throttled.
> PP-2939 Use the new direct debit run e2e job on PR merge

- common/utils/certificates/custom-certificate.js
We attempted to grab everything in the CERTS_PATH and use it as a CA, including directories...
When we added `/etc/ssl/certs/java/cacerts` we attempted to use `/etc/ssl/certs/java` as a CA...
> BAU: Fix certificate parsing

- app/setup/get.njk
- common/browsered/field-validation-checks.js
- common/browsered/field-validation-checks.test.js
- Relaxed sort code validation: now it accepts any combination of whitespace, dashes and digits, exactly six digits
- Removed usage of `module.exports` as described in https://github.com/alphagov/pay-frontend/commit/0b2a1516f9ab91c013b9dc466bc8e1a14c433254
- Error message improvements
with @alexbishop1
> PP-3080 Relaxed sort code validation

- app/confirmation/get.controller.js
- app/confirmation/get.controller.tests.js
This PR adds better sort code formatting.
As per GOV.UK styling guide for sort code we should use spaces in sort codes - 60 70 80 (not 60-70-80 and not 607080)
More information: https://www.gov.uk/guidance/style-guide/a-to-z-of-gov-uk-style#bank-details
> PP-3080 Better sort code formatting

- app/confirmation/get.controller.js
- app/confirmation/get.controller.tests.js
- app/confirmation/index.js
- app/confirmation/post.controller.js
- app/confirmation/post.controller.tests.js
- app/secure/get.post.controller.js
- app/secure/get.post.controller.tests.js
- app/setup/get.controller.js
- app/setup/get.controller.tests.js
- app/setup/index.js
- app/setup/post.controller.js
- app/setup/post.controller.tests.js
- common/clients/base-client/wrapper.js
- common/clients/connector-client.js
- common/config/cookies.js
- common/config/cookies.test.js
- common/middleware/csrf.js
- common/middleware/csrf.tests.js
- common/middleware/get-payment-request.js
- common/middleware/get-payment-request.tests.js
- server.js
- test/fixtures/payments-fixtures.js
- test/test.env
- test/test_helpers/cookie-helper.js
- We were sticking the payment journey's info (ie. payment request, form
values, confirmation details) in `req.session`. This helped us move
faster, but it won't allow multiple payments going through.
- This PR name spaces cookies on the payment request external id. So, for
two payments from the same browser, the cookie will have the shape of:
```
req: {
direct_debit_frontend_state: {
externalId1: {
paymentRequest: [Object]
...
},
externalId2: {
paymentRequest: [Another Object]
...
}
}
}
```
- Introducing two session keys in similar fashion to cc frontend, this
would allow us to rotate the encryption key of tokens. Session key 1
is always favoured over 2, if present.
- Propagating request id to the dd client. Correlation id is present
in all requests via a middleware, so …
> PP-3044 Handle multiple payments in session, and set request id in logs

- common/browsered/input-confirm.js
This is old news but it gets forgotten. If you wrap it in this it
converts it into an array and it works fine
you could do it with a spread operator but this breaks it in old IE
> BAU - nodeList cannot be iterated by forEach on Phantom

- app/direct-debit-guarantee/get.controller.js
- app/direct-debit-guarantee/get.controller.tests.js
- app/direct-debit-guarantee/get.njk
- app/direct-debit-guarantee/index.js
- app/setup/get.controller.tests.js
- app/setup/get.njk
- If we are in a payment journey, we show back links bringing to the enter direct debit details page
- If we are not in a payment journey (ie. link to the guarantee in an email sent to the user) we don't show back links because there's no "back" page to go to
_Steps to test or reproduce:_
> PP-3360 Fix back links for direct debit guarantee

- common/browsered/input-confirm.js
PhantomJS doesn’t like `.closest()` so we have to add the polyfill
> PP-3586 - added polyfill for closest to input-confirm

- common/browsered/field-validation.js
- common/browsered/index.js
- common/browsered/input-confirm.js
Temporary fix for failing smoke tests because of the use the closest element not supported in PhantomJS.
A Polyfill for closest element has been embedded in the code which can be removed once smoke tests stop relying on phantomjs.
See https://github.com/alphagov/pay-selfservice/pull/702
with @ckalista
> PP-3586 Temporary fix for failing smoke tests

- common/browsered/input-confirm.js
The email field has some Javscript validation that uses the `.after()` function which is unfortunately not supported in PhantomJS. Instead of introducing a polyfill here, the validation has simply been rewritten slightly not to use `.after()`.
> PP-3586 Fix for flaky smoke tests

- Dockerfile
When we initially integrated Chamber we needed openssl, not we use different way to connect with Chamber.
We don't need to install openssl this way anymore.
with @rhowe-gds
> PP-3666 Remove openssl installation from Dockerfile

- app/secure/get.post.controller.js
- app/secure/get.post.controller.tests.js
- common/classes/GatewayAccount.class.js
- common/classes/PaymentRequest.class.js
- common/clients/connector-client.js
- test/fixtures/payments-fixtures.js
We need to expose gateway account to be able to distinguish between `TEST` and `LIVE` accounts as well as to get the service name to display in the header.
This PR adds the gatewayAccount to the session.
When we introduce Pact we need to cover the connector client with tests.
> PP-3545 Expose gateway account

- app/cancel/get.controller.js
- app/cancel/get.controller.tests.js
- app/cancel/get.njk
- app/cancel/index.js
- app/confirmation/get.controller.tests.js
- app/confirmation/get.njk
- app/router.js
- app/setup/get.controller.tests.js
- app/setup/get.njk
- common/clients/connector-client.js
- test/fixtures/payments-fixtures.js
- Created a cancel controller which calls dd connector to cancel a payment journey. After
the user presses cancel, we display a 'error' page explaining that no money was taken, and
showing a link to the service (return url)
> PP-3649 Cancel links now work

- app/cancel/get.controller.tests.js
- app/cancel/index.js
- app/change-payment-method/get.controller.tests.js
- app/change-payment-method/index.js
- app/confirmation/get.controller.tests.js
- app/confirmation/index.js
- app/confirmation/post.controller.tests.js
- app/setup/get.controller.tests.js
- app/setup/index.js
- app/setup/post.controller.tests.js
- common/middleware/get-gateway-account.js
- common/middleware/get-gateway-account.tests.js
- common/middleware/get-payment-request.js
- common/middleware/get-payment-request.tests.js
- common/templates/includes/propositional_navigation.njk
- common/templates/layout.njk
- npm-shrinkwrap.json
- package.json
- test/fixtures/payments-fixtures.js
* Use of a middleware called `get-gateway-account` to retrieve the gateway account data of the current payment request. Once the data is loaded from dd-connector it is cached for 15 mins by default for later use. The data is then exposed under `res.locals.gatewayAccount`.
* Updated the template to show the service name that is made available by the middleware.
> PP-3670 Display service name on frontend

- app/confirmation/get.controller.js
- app/confirmation/get.controller.tests.js
- app/direct-debit-guarantee/anchor.njk
- app/direct-debit-guarantee/get.controller.js
- app/direct-debit-guarantee/get.controller.tests.js
- app/direct-debit-guarantee/get.njk
- app/direct-debit-guarantee/index.js
- app/setup/get.controller.js
- app/setup/get.controller.tests.js
- Make Direct Debit Guarantee return to the page from where it was called
- In story review, it was discovered that when navigating back from `direct-debit-guarantee` page, the user was sent always to `setup` page. That means that when a user will land on `direct-debit-guarantee` from `confirmation` it will be sent to `setup` when goes back. Now, it will be sent back to where it came from, based on `paymentAction` parameter.
> PP-3258 Fix dead links

- app/confirmation/get.controller.tests.js
- app/confirmation/get.njk
- app/setup/get.controller.js
- app/setup/get.controller.tests.js
- common/classes/PaymentRequest.class.js
- test/fixtures/payments-fixtures.js
We are now allowing the user to edit dd details after having reached the confirmation page. We can reinstate the link to go back to the enter dd details page.
Going back via link will not pre-populate the form for now, until connector is merged.
> PP-3701 Add back link to confirmation page

- app/confirmation/post.controller.js
- app/confirmation/post.controller.tests.js
- common/clients/connector-client.js
- We are hashing account number and sort code in connector. This means
we don't have those details when the user confirms their details, unless
frontend passes them back to connector
> PP-3701 Pass confirmation details to connector

- app/setup/post.controller.tests.js
- common/clients/connector-client.js
We now create or update a payer, hence we should use a `PUT` and not a `POST` to do so.
> PP-3701 Frontend uses PUT to create/update a payer

- app/setup/post.controller.js
- app/setup/post.controller.tests.js
- common/clients/connector-client.js
- We are introducing a new endpoint in connector which validates bank account details.
For sandbox, those will always be valid. For gocardless, we are going to call them and they
will return the result of the modulus checking algorithm, together with additional info
like bank name, which _could_ be used in the future for on-blur validation
- We submit details only if our "local" validation and online validation actually pass
- If connector returns that the details are invalid, we display an error
> PP-3714 Call connector to validate bank account details

- app/confirmation/get.controller.js
- app/confirmation/get.controller.tests.js
- When navigating from setup directly to confirmation page,  without
adding any details we should show the error page, instead of a 500 and
an exception dump
> PP-3700 Fix navigation to page confirmation

- app/setup/get.njk
- app/setup/post.controller.js
- app/setup/post.controller.tests.js
- common/browsered/field-validation-checks.js
- common/browsered/field-validation-checks.test.js
- common/browsered/field-validation.js
- common/utils/payer-validator/index.js
- Client side field validation on DD didn't allow for custom error messages on from the validator function, this means that if you're validating a field against more than one validator you can only show one error message, this is sad. So now the validator passes back a message which is used as the error message, if it’s not present it defaults to the data attribute error message that is set.
- We were previously hardcoding the error message in the template. As we now can have multiple reasons a single input field might be invalid, we need to be able to specify the error message dynamically.
- Added hint text + slight change of copy in error messages related to sort code and account number
- We should really share the validation in js commons between our microservices (shameless 🔌) 
with …
> PP-3714 Add hint text and dynamic error messages for field validation 

- app/cancel/get.controller.tests.js
- app/cancel/index.js
- app/change-payment-method/index.js
- app/confirmation/get.controller.js
- app/confirmation/get.controller.tests.js
- app/confirmation/index.js
- app/confirmation/post.controller.tests.js
- app/setup/get.controller.tests.js
- app/setup/index.js
- app/setup/post.controller.tests.js
- common/middleware/check-secure-cookie/check-secure-cookie.js
- common/middleware/check-secure-cookie/check-secure-cookie.tests.js
- common/middleware/correlation-header/correlation-header.js
- common/middleware/csrf/csrf.js
- common/middleware/csrf/csrf.tests.js
- common/middleware/get-gateway-account/get-gateway-account.js
- common/middleware/get-gateway-account/get-gateway-account.tests.js
- common/middleware/get-mandate/get-mandate.js
- common/middleware/get-mandate/get-mandate.tests.js
- common/middleware/get-service/get-service.js
- common/middleware/get-service/get-service.tests.js
- common/middleware/mandate-state-enforcer/mandate-state-enforcer.js
- common/middleware/mandate-state-enforcer/mandate-state-enforcer.tests.js
- common/response.js
- common/templates/error.njk
- common/templates/mandate_state_page.njk
- server.js
This PR introduces a mandate state enforcer, a middleware to ensure that the current state of the mandate is compatible with where the user is in the flow https://github.com/alphagov/pay-direct-debit-frontend/pull/90/files#diff-08a2dcbb1afa1c62e78f72a9c4b5dde5
It does this in a similar way to how card frontend does it, by defining for each page a set of compatible mandate states. NB. We have only paid attention to mandate state rather than both payment and mandate since my understanding is that in the case of one off payments the state of the payment request mirrors that of the mandate.
As it stands the compatible states for each page are as follows
| Page        | Compatible States           |
| ------------- |:-------------:| 
| setup      | started |
| confirmation      | started …
> PP-3838 Mandate state enforcer

- common/middleware/mandate-state-enforcer/mandate-state-enforcer.js
We introduced a new state, EXPIRED, in dd connector. This commit
adds custom message for when a user tries to view setup/confirm
with an expired mandate.
> PP-3838 Add custom message for expired mandate in enforcer

- app/cancel/get.controller.js
- app/change-payment-method/index.js
- app/confirmation/get.controller.js
- app/confirmation/get.controller.tests.js
- app/confirmation/get.njk
- app/setup/get.controller.js
- app/setup/get.controller.tests.js
- app/setup/get.njk
- common/classes/Mandate.class.js
- common/classes/Transaction.class.js
- common/clients/connector-client.js
- common/middleware/get-mandate/get-mandate.js
- test/fixtures/payments-fixtures.js
Handle ON_DEMAND payments:
- Changed the `Mandate.type` to be `Mandate.mandate_type` for consistency
- Adapted pages to `ON_DEMAND` payments
- Fixed transactions to work with `ON_DEMAND` payments and fixed the tests
with @georgeracu and @alexbishop1
> PP-3671 Handle ON_DEMAND payments

- app/cancel/get.controller.tests.js
- app/confirmation/get.controller.tests.js
- app/confirmation/post.controller.tests.js
- app/setup/get.controller.tests.js
- app/setup/post.controller.tests.js
- common/classes/Mandate.class.js
- common/middleware/mandate-state-enforcer/mandate-state-enforcer.js
- common/middleware/mandate-state-enforcer/mandate-state-enforcer.tests.js
- test/fixtures/payments-fixtures.js
- We want a more fine grained control over mandate states in order to
show error messages which make sense. We need to decide on the internal
mandate state rather than the external.
> PP-3838 State enforcer should decide on internal mandate state

- common/middleware/mandate-state-enforcer/mandate-state-enforcer.js
- common/middleware/mandate-state-enforcer/mandate-state-enforcer.tests.js
Handling mandate expired as mandate failed, showing the same error message.
> PP-3838 Handle mandate expired as failed

- package-lock.json
Ran 'npm audit fix' to resolve https://nodesecurity.io/advisories/566
See what `npm audit` says now, and see if direct-debit-frontend still works
> PP-4387: Remove vulnerable hoek module

- app/setup/post.controller.js
- app/setup/post.controller.tests.js
When submitting the direct debit setup page we were not handling the
case when there was an error calling connector to verify the bank
details.
Handle this, and improve controller code at the same time.
> PP-5269 Handle error validating bank details

- common/browsered/field-validation-checks.js
- common/browsered/field-validation-checks.test.js
Not sure why this was set to 6-8
> PP-5265 - Valid account numbers should be 8-10 digits

- app/setup/get.njk
- common/browsered/field-validation-checks.js
- common/browsered/field-validation-checks.test.js
Account numbers are in fact between 6 and 8 digits long
> PP-5265 fix valid account number boundaries revert

- common/middleware/mandate-state-enforcer/mandate-state-enforcer.js
- common/middleware/mandate-state-enforcer/mandate-state-enforcer.tests.js
Replace `EXPIRED` with `USER_SETUP_EXPIRED`
Remove conditions and tests for `PENDING` and `USER_CANCEL_NOT_ELIGBLE` as
the internal states no longer exists.
Renamed `SUBMITTED` to `SUBMITTED_TO_PROVIDER` and added new internal
state of `SUBMITTED_TO_BANK` with tests.
Align heading and message for `ACTIVE` with submitted statuses.
> PP-5534 Update internal states

- common/assets/sass/modules/_button.scss
- common/browsered/field-validation.js
Because we have JS validating on blur there is an edge case (read more at PP-5533) where when clicking the submit button when you‘re focused on a errored field causes the page to jump up and then the click event misses the button.
So we can fix this by making the button invisibly bigger when it becomes active.
> PP - 5533 fix field validation bugs

- app/confirmation/get.njk
@stephencdaly good suggestion and Conor agrees, this moves email to the last row (and adds a missing `:`).
> PP-5532 Move Email to last line on mandate confirmation page

- app/setup/post.controller.js
- app/utils/logger.js
- common/clients/base-client/base-client.js
- common/middleware/check-secure-cookie/check-secure-cookie.js
- common/middleware/csrf/csrf.js
- common/middleware/get-gateway-account/get-gateway-account.js
- common/middleware/get-mandate/get-mandate.js
- common/middleware/get-service/get-service.js
- common/middleware/mandate-state-enforcer/mandate-state-enforcer.js
- common/response.js
- common/utils/request-logger.js
- server.js
- start.js
Use Winston's child function and override the logger attribute with the name
of the file in each place we're using a logger. This will help us track down errors to the file
that they're being thrown in (like we do with Java apps).
How to test
Check the log output in the tests to check that `logger` corresponds to the correct file.
> PP-5613 Add filename to logger

- app/utils/logger.js
- app/utils/timestamp-format.js
Timestamps should be logged as '@timestamp' (see https://gds-way.cloudapps.digital/manuals/logging.html#content).
@RoryMalcolm @oswaldquek
> PP-5511: Log timestamp according to the GDS standard

- app/utils/logger-format.js
- app/utils/logger.js
Changing as this is the term used in current splunk searches.
> PP-5735 Change 'label' key in logs to 'container'

- app/cancel/get.controller.js
- app/change-payment-method/get.controller.js
- app/confirmation/post.controller.js
- app/router.js
- app/secure/get.post.controller.js
- app/setup/post.controller.js
- common/middleware/get-gateway-account/get-gateway-account.js
- common/middleware/get-mandate/get-mandate.js
- common/middleware/get-service/get-service.js
- common/response.js
- package-lock.json
- package.json
- server.js
Adding sentry with minimal disruption to
current error handling.
Add sentry to server.js.
Add default request handler and error handler
as first (and currently only) error middleware.
Use renderErrorView as central point to emit
events to Sentry.
In order to do this we pass the original error
in where available. Only send errors to sentry when
status code is 500 or greater, since we don't want
to be alerted on client errors.
with @mrlumbu
Notes:
We have added a temporary end-point to make testing of the Sentry integration easier `'/sentry-test-default'` and `'/sentry-test`. These will be removed once we're satisfied that it is working.
> PP-5726 Integrate app with Sentry

- app/utils/logger.js
- app/utils/winstonSentryTransport.js
- common/response.js
- server.js
Currently dd-frontend sends all logs to Sentry; we only want it to send logs at
ERROR level.
> PP-5809: Only send logs at ERROR level to Sentry

- common/middleware/logging_middleware.js
Logging middleware was throwing an error when attempting to log, as
`logging.requestLogFormat` in pay-js-commons had been modified, but
the consuming module hadn't been updated to work with the changes.
> BAU Fix request logging

- common/templates/includes/analytics.njk
Complying with ICO guidance around cookie consent we can't set non-essential cookies without consent being granted. In the short term then we have to disable Google Analytics as it stores cookies.
> PP-5977 Disable google analytics

- .travis.yml
Appmetrics package requires libconf to be present in the build environment.
> PP-6037: Add libconf appmetrics build dependency in Travis build environment

- env-map.yml
- manifest.yml
This supports mapping of data provided by user-provided backing
services on PaaS to application environment variables required
by the application.
> PP-6085: Add env-map buildpack

- env-map.yml
- manifest.yml
Binds dd-frontend to secrets service added in alphagov/pay-omnibus#105
Adds environment variable mappings to `env-map.yml` to transpose VCAP_SERVICE data to application environment variables.
> PP-6127: Bind app to PaaS secrets service

- env-map.yml
- manifest.yml
Set the METRICS_HOST and METRICS_PORT from the app-catalog to send
metrics to the carbon-relay app.
> PP-6254 Add carbon-relay

- package.json
PaaS no longer support engine version 12.14.1 so updating to the latest
12.* version that is supported. This setting is currently only used by
cf to select an appropriate buildpack.
> PP-6254 Update engine version for PaaS

- Jenkinsfile
Description:
- Before we can turn off the direct debit smoke test we need to ensure that no pipeline calls it. This ensures that the direct-debt-frontend Jenkins pipeline doesn't call the direct debit smoke Jenkins function.
- This also ensures that the direct debit portion of the end to end test suit won't be run
> PP-6763 - Remove direct debit smoke and end to end test from direct-debit-frontend Jenkins pipeline

- .github/dependabot.yml
- remove label from dependabot labels. since we no longer merge dependabot PRs for dd apps, we don't want them to appear on the list either.
> BAU remove govuk pay label
